#Define variable configuration
output_save_file_name: "default"
output_save_path: "outputs/default/"    # Where to save the output

# Model config
model: "qwen2.5"
max_tokens: 4096
max_chunk_size: 1000
batch_size: 1
ocr_model: "mistral7b"
ocr_extraction_model: "qwen2.5"
ocr_temperature: 0.01
transcription_temperature: 0.01
timeout: 4 # Number of tries
# Data reader config
crop: True
padding: 100.0
resize_factor: 1
remove_area_perc: 0.01
middle_margin_perc: 0.20
has_columns: False
double_pages: False
# define to inherit any missing prompts from the default prompt
inherit_default: False
# Path to default file if inheriting from another custom prompt
default_file: None